#######################
#      Site info      #
#######################
title: phvmous [ fey-muhs ] | "something need doing?"
name: Thomas Pham
email: dtmstyle7@gmail.com
description: > # description of the website
  The personal website of Thomas Pham, a software engineer and master's student at UPenn.
footer_text: > # text that will appear next to the Copyright symbol
  phvmous. All rights reserved. Made with ❤️ on Jekyll
keywords: jekyll-theme, jekyll, portfolio, minnie
icon: 🔥 # the website's favicon
lang: en # language setting, i.e. en for English, fr for French

#######################
#    Site settings    #
#######################
remote_theme: phvmous/minnie
url: https://phvmous.github.io # the hostname of your site, i.e. if Github pages then https://your-username.github.io
github: phvmous
linkedin: phamous


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap