#######################
#      Site info      #
#######################
title: minnie [ minh-ney ] # the title of the website
tagline: "a fast lightweight minimal jekyll theme"
brand: minnie
brand_tag: "[ minh-ney ]"
name: Paul Smith
email: paulpular@gmail.com
description: > # meta data description
  a fast lightweight minimal jekyll theme
footer_text: > # text that will appear at the bottom next to the Copyright statement
  minnie. Made with ❤️ on Jekyll.
keywords: jekyll-theme, jekyll, portfolio, minnie
icon: 🔥 # the favicon, you can be hip and use an emoji
lang: en # language setting, i.e. en for English, fr for French

#######################
#    Site settings    #
#######################
remote_theme: phvmous/minnie
url: https://your-github.github.io # the hostname of your site, i.e. if Github pages then https://your-username.github.io
github: paulsmith # github username
linkedin: paulsmith # linkedin username
nav_menu: false # enable to have navigation menu links
dark_mode_toggle: true # enable to allow the dark mode toggle button to appear in the nav bar, default is true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap